USE QUAN_LY_SINH_VIEN
go 
DECLARE @MAKHOA VARCHAR(10), @TENKHOA NVARCHAR(50), @STT INT, @HOTEN NVARCHAR(50), @HOCVI NVARCHAR(50), @HOCHAM NVARCHAR(50)

DECLARE KHOA_CUR CURSOR 
FOR SELECT KHOA.MAKHOA, KHOA.TENKHOA 
FROM KHOA

OPEN KHOA_CUR
FETCH NEXT FROM KHOA_CUR INTO @MAKHOA, @TENKHOA 
SELECT @STT = 1
WHILE @@FETCH_STATUS = 0
	BEGIN 
		
		PRINT '----------- DANH SACH GIAO VIEN KHOA: ' + @TENKHOA

		DECLARE GV_CUR CURSOR
		FOR SELECT GIAOVIEN.HOTEN, GIAOVIEN.HOCVI, GIAOVIEN.HOCHAM  --, GIAOVIEN.MAKHOA
		FROM GIAOVIEN
		WHERE GIAOVIEN.MAKHOA = @MAKHOA
		OPEN GV_CUR
		FETCH NEXT FROM GV_CUR INTO @HOTEN, @HOCVI, @HOCHAM
		WHILE @@FETCH_STATUS = 0 
			BEGIN 
				PRINT CAST(@STT AS NVARCHAR(10)) + '-----' + @HOTEN + '-----' + @HOCVI  + '-----' + @HOCHAM
				FETCH NEXT FROM GV_CUR INTO @HOTEN, @HOCVI, @HOCHAM
				SELECT @STT +=1 
			END
			CLOSE GV_CUR
			DEALLOCATE GV_CUR



		FETCH NEXT FROM KHOA_CUR INTO @MAKHOA, @TENKHOA 

	END

CLOSE KHOA_CUR
DEALLOCATE KHOA_CUR



DROP SEQUENCE INCRE

CREATE SEQUENCE INCRE
AS INT 
START WITH 0
INCREMENT BY 1;
GO
 





 DECLARE @COUNT INT = 1, @TempValues INT;
 WHILE @COUNT <= 10
	BEGIN
		SELECT @TempValues= NEXT VALUE FOR INCRE 
		INSERT INTO MONHOC(MAMH, TENMH) VALUES
			('M' + CAST(@TempValues AS NVARCHAR(10)) , 'Mon '+ CAST(@TempValues AS NVARCHAR(10)) );
		SELECT @COUNT +=1

	END






