--1. Học viên thi một môn tối đa 3 lần.
GO 
CREATE OR ALTER TRIGGER T_LANTHI 
ON KETQUATHI
INSTEAD OF INSERT
AS
BEGIN
	IF EXISTS (
		SELECT 1 
		FROM KETQUATHI INNER JOIN inserted I ON  KETQUATHI.MAHV = I.MAHV
											AND KETQUATHI.MAMH = I.MAMH
											
		GROUP BY I.MAHV, I.MAMH
		HAVING COUNT(*) >= 3)


		BEGIN
			RAISERROR ('THI QUA 3 LAN', 16,1)
			ROLLBACK TRANSACTION
		END

	ELSE
		BEGIN
			INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, KQUA, DIEM)
			SELECT I.MAHV, I.MAMH, I.LANTHI, I.NGTHI, I.KQUA, I.DIEM
			FROM inserted I
			PRINT 'THANH CONG'
		END

END
GO

SELECT *
FROM KETQUATHI
WHERE MAHV ='K1102'

INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, KQUA, DIEM) VALUES 
	('K1102'	,'CSDL',	4	,'2006-12-28',	'Khong Dat'	,4.5)


DROP TRIGGER T_HOCKI

--2. Học kỳ chỉ có giá trị từ 1 đến 3.
GO
CREATE OR ALTER TRIGGER T_GIANGDAY
ON GIANGDAY
INSTEAD OF INSERT 
AS
BEGIN
	IF EXISTS (
		SELECT 1
		FROM inserted I
		WHERE I.HOCKY >3 OR HOCKY < 1)
		
		BEGIN 
			RAISERROR ('HOC KI TU 1 - 3 ', 16,1)
			ROLLBACK TRANSACTION
		END


	ELSE
		BEGIN
			INSERT INTO GIANGDAY(MALOP, MAMH, MAGV, HOCKY, NAM, TUNGAY, DENNGAY)
			SELECT I.MALOP, I.MAMH, I.MAGV, I.HOCKY, I.NAM, I.TUNGAY, I.DENNGAY
			FROM inserted I
			PRINT 'THANH CONG'
		END
END
GO

SELECT *
FROM GIANGDAY

INSERT INTO GIANGDAY(MALOP, MAMH, MAGV, HOCKY, NAM, TUNGAY, DENNGAY) VALUES
	('K11',	'CTRR',	'GV05',	21	,2006,	'2006-06-01',	'2006-07-15')




--3. Học vị của giáo viên chỉ có thể là “CN”, “KS”, “Ths”, ”TS”, ”PTS”.

GO
CREATE OR ALTER TRIGGER T_GIAOVIEN
ON GIAOVIEN
INSTEAD OF INSERT 
AS
BEGIN
	IF EXISTS (
		SELECT 1
		FROM inserted I
		WHERE I.HOCVI NOT IN ('CN', 'KS', 'Ths', 'TS', 'PTS'))
		
		BEGIN 
			RAISERROR ('Học vị của giáo viên chỉ có thể là “CN”, “KS”, “Ths”, ”TS”, ”PTS”', 16,1)
			ROLLBACK TRANSACTION
		END


	ELSE
		BEGIN
			INSERT INTO GIAOVIEN(MAGV, HOTEN, HOCVI, HOCHAM,  GIOITINH, NGAYSINH, NGVAOLAM, HESO, MUCLUONG, MAKHOA)
			SELECT I.MAGV, I.HOTEN, I.HOCVI, I.HOCHAM, I.GIOITINH, I.NGAYSINH, I.NGVAOLAM, I.HESO,I.MUCLUONG,I.MAKHOA
			FROM inserted I
			PRINT 'THANH CONG'
		END
END
GO



SELECT *
FROM GIAOVIEN

INSERT INTO GIAOVIEN(MAGV, HOTEN, HOCVI, HOCHAM,  GIOITINH, NGAYSINH, NGVAOLAM, HESO, MUCLUONG, MAKHOA) VALUES
('GV011',	'Ho Thanh Son',	'ABC',	'GS',	0	,'1950-05-02',	'2004-01-11',	5,	2250000	,'KHMT')




--4. Học viên ít nhất là 18 tuổi.


GO
CREATE OR ALTER TRIGGER T_HOCVIEN
ON HOCVIEN
INSTEAD OF INSERT 
AS
BEGIN
	IF EXISTS (
		SELECT 1
		FROM inserted I
		WHERE YEAR(GETDATE())- YEAR(I.NGSINH) <18)
		
		BEGIN 
			RAISERROR ('Học viên ít nhất là 18 tuổi.', 16,1)
			ROLLBACK TRANSACTION
		END


	ELSE
		BEGIN
			INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, NOISINH, MALOP)
			SELECT			I.MAHV, I.HO, I.TEN, I.NGSINH, I.NOISINH, I.MALOP 
			FROM inserted I
			PRINT 'THANH CONG'
		END
END
GO
 

SELECT *
FROM HOCVIEN
WHERE YEAR(GETDATE())- YEAR(NGSINH) <18

INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, NOISINH, MALOP) VALUES
('K11011',	'Tran',	'Duc Bo',	'2024-02-02',	'Ben Tre',	'K11')




--5. Giảng dạy một môn học ngày bắt đầu (TUNGAY) phải nhỏ hơn ngày kết thúc
--(DENNGAY).


GO
CREATE OR ALTER TRIGGER T_GIANGDAY
ON GIANGDAY
INSTEAD OF INSERT 
AS
BEGIN
	IF EXISTS (
		SELECT 1
		FROM inserted I
		WHERE I.HOCKY >3 OR HOCKY < 1)
		
		BEGIN 
			RAISERROR ('HOC KI TU 1 - 3 ', 16,1)
			ROLLBACK TRANSACTION
		END



		IF EXISTS (
					SELECT 1
					FROM inserted I 
					WHERE I.TUNGAY >= I.DENNGAY
					)


			BEGIN
				RAISERROR ('Giảng dạy một môn học ngày bắt đầu phải nhỏ hơn ngày kết thúc', 16,1)
			ROLLBACK TRANSACTION
			END


	ELSE
		BEGIN
			INSERT INTO GIANGDAY(MALOP, MAMH, MAGV, HOCKY, NAM, TUNGAY, DENNGAY)
			SELECT I.MALOP, I.MAMH, I.MAGV, I.HOCKY, I.NAM, I.TUNGAY, I.DENNGAY
			FROM inserted I
			PRINT 'THANH CONG'
		END
END
GO


INSERT INTO GIANGDAY(MALOP, MAMH, MAGV, HOCKY, NAM, TUNGAY, DENNGAY) VALUES
	('K111',	'CTRR',	'GV05',	21	,2006,	'2012-06-01',	'2006-07-15')




--6. Giáo viên khi vào làm ít nhất là 22 tuổi.
GO
CREATE OR ALTER TRIGGER T_GIAOVIEN
ON GIAOVIEN
INSTEAD OF INSERT
AS
BEGIN
	IF EXISTS(
		SELECT 1 
		FROM inserted I
		WHERE YEAR(GETDATE()) - YEAR( I.NGAYSINH) <22)
		
		BEGIN
			RAISERROR ('Giáo viên khi vào làm ít nhất là 22 tuổi.', 16,1)
			ROLLBACK TRANSACTION
		END

	ELSE 
		BEGIN
			INSERT INTO GIAOVIEN(MAGV, HOTEN,HOCVI,HOCHAM ,GIOITINH, NGAYSINH, NGVAOLAM, HESO, MUCLUONG, MAKHOA)
			SELECT I.MAGV, I.HOTEN,I.HOCVI,I.HOCHAM ,I.GIOITINH, I.NGAYSINH, I.NGVAOLAM, I.HESO, I.MUCLUONG, I.MAKHOA
			FROM inserted I
		END

END
GO



SELECT *
FROM GIAOVIEN

INSERT INTO GIAOVIEN(MAGV, HOTEN,HOCVI,HOCHAM ,GIOITINH, NGAYSINH, NGVAOLAM, HESO, MUCLUONG, MAKHOA) VALUES
('GV150',	'Nguyen Bao Thien Y',	'TS',	'PSG',	1,	'2020-12-04',	'2005-05-15',	4,	1800000	,'KTMT')



--7. Tất cả các môn học đều có số tín chỉ lý thuyết và tín chỉ thực hành chênh lệch
--nhau không quá 3.

GO
CREATE OR ALTER TRIGGER T_MONHOC
ON MONHOC
INSTEAD OF INSERT
AS 
BEGIN
	IF EXISTS (	
				SELECT 1
				FROM inserted I
				WHERE I.TCLT - I.TCTH > 3
					OR I.TCTH - I.TCLT > 3)
		BEGIN
			RAISERROR ('Tất cả các môn học đều có số tín chỉ lý thuyết và tín chỉ thực hành chênh lệch nhau không quá 3.',16,1)
			ROLLBACK TRANSACTION
		END

	ELSE 
		BEGIN
			INSERT INTO MONHOC(MAMH, TENMH, TCLT, TCTH,MAKHOA)
			SELECT I.MAMH, I.TENMH, I.TCLT, I.TCTH, I.MAKHOA
			FROM inserted I
		END

END
GO

SELECT * 
FROM MONHOC

INSERT INTO MONHOC(MAMH, TENMH, TCLT, TCTH,MAKHOA) VALUES
('CTRR2',	'Cau truc roi rac',	5,	0,	'KTMT')







--8. Mỗi học kỳ của một năm học, một lớp chỉ được học tối đa 3 môn.



GO
CREATE OR ALTER TRIGGER T_GIANGDAY
ON GIANGDAY
INSTEAD OF INSERT 
AS
BEGIN
	IF EXISTS (
		SELECT 1
		FROM inserted I
		WHERE I.HOCKY >3 OR HOCKY < 1)
		
		BEGIN 
			RAISERROR ('HOC KI TU 1 - 3 ', 16,1)
			ROLLBACK TRANSACTION
		END



		IF EXISTS (
					SELECT 1
					FROM inserted I 
					WHERE I.TUNGAY >= I.DENNGAY
					)


			BEGIN
				RAISERROR ('Giảng dạy một môn học ngày bắt đầu phải nhỏ hơn ngày kết thúc', 16,1)
			ROLLBACK TRANSACTION
			END


		IF EXISTS(
				SELECT 1
				FROM inserted I JOIN GIANGDAY G ON I.MALOP = G.MALOP 
				GROUP BY I.MAMH, I.HOCKY
				HAVING COUNT(*) >=3)

			BEGIN
				RAISERROR (' Mỗi học kỳ của một năm học, một lớp chỉ được học tối đa 3 môn.', 16,1)
			ROLLBACK TRANSACTION
			END

	ELSE
		BEGIN
			INSERT INTO GIANGDAY(MALOP, MAMH, MAGV, HOCKY, NAM, TUNGAY, DENNGAY)
			SELECT I.MALOP, I.MAMH, I.MAGV, I.HOCKY, I.NAM, I.TUNGAY, I.DENNGAY
			FROM inserted I
			PRINT 'THANH CONG'
		END
END
GO


INSERT INTO GIANGDAY(MALOP, MAMH, MAGV, HOCKY, NAM, TUNGAY, DENNGAY) VALUES
	('K11',	'PTTKTT',	'GV05',	1	,2006,	'2006-06-01',	'2006-07-15')

SELECT  * 
FROM GIANGDAY



--9. Sỉ số của một lớp bằng với số lượng học viên thuộc lớp đó.
GO
CREATE OR ALTER TRIGGER T_SISO
ON LOP
INSTEAD OF UPDATE 
AS
BEGIN
	IF EXISTS (
				SELECT 1
				FROM inserted I
				WHERE I.SISO <> (
								SELECT COUNT(*)
								FROM HOCVIEN
								WHERE HOCVIEN.MALOP = I.MALOP))

		BEGIN
			RAISERROR ('Sỉ số của một lớp bằng với số lượng học viên thuộc lớp đó.', 16,1)
			ROLLBACK TRANSACTION
		END


	ELSE
		BEGIN 
			UPDATE LOP
			SET 
				
				LOP.TENLOP = I.TENLOP,
				LOP.TRGLOP = I.TRGLOP,
				LOP.SISO = I.SISO,
				LOP.MAGVCN = I.MAGVCN
			FROM inserted I
		END
END
GO

SELECT *
FROM LOP

UPDATE LOP
	SET SISO = 10


SELECT COUNT(*)
FROM HOCVIEN
WHERE MALOP ='K11'


--10. Trong quan hệ DIEUKIEN giá trị của thuộc tính MAMH và MAMH_TRUOC trong
--cùng một bộ không được giống nhau (“A”,”A”) và cũng không tồn tại hai bộ
--(“A”,”B”) và (“B”,”A”).
GO
CREATE OR ALTER TRIGGER T_DIEUKIEN
ON DIEUKIEN
INSTEAD OF INSERT
AS 
BEGIN
	IF EXISTS (
				SELECT 1
				FROM inserted I JOIN DIEUKIEN DK ON DK.MAMH = I.MAMH
												
				WHERE I.MAMH_TRUOC = (SELECT TOP(1) MAMH
								FROM DIEUKIEN
								WHERE DIEUKIEN.MAMH_TRUOC = I.MAMH))

		BEGIN 
			RAISERROR ('(“A”,”B”) và (“B”,”A”)', 16,1)
			ROLLBACK TRANSACTION
		END

	
	IF EXISTS (
				SELECT 1
				FROM inserted I JOIN DIEUKIEN DK ON DK.MAMH = I.MAMH
												
				WHERE I.MAMH = I.MAMH_TRUOC)

		BEGIN 
			RAISERROR ('MA MON HOC = MA MON HOC TRUOC', 16,1)
			ROLLBACK TRANSACTION
		END

	ELSE 
		BEGIN
			INSERT INTO DIEUKIEN(MAMH, MAMH_TRUOC )
			SELECT I.MAMH, I.MAMH_TRUOC
			FROM inserted I
		END


END
GO


SELECT * 
FROM DIEUKIEN

INSERT INTO DIEUKIEN(MAMH, MAMH_TRUOC ) VALUES
('CTDLGT','CSDL')



--11. Các giáo viên có cùng học vị, học hàm, hệ số lương thì mức lương bằng nhau.

GO
CREATE OR ALTER TRIGGER T_GIAOVIEN
ON GIAOVIEN
INSTEAD OF INSERT
AS 
BEGIN
	IF EXISTS (
				SELECT 1
				FROM inserted I, GIAOVIEN GV
				WHERE I.HOCVI = GV.HOCVI
					AND I.HOCHAM = GV.HOCHAM
					AND I.HESO = GV.HESO
					AND I.MUCLUONG <> GV.MUCLUONG
				)

		BEGIN 
			RAISERROR ('Các giáo viên có cùng học vị, học hàm, hệ số lương thì mức lương bằng nhau.', 16,1)
			ROLLBACK TRANSACTION
		END


	ELSE 
		BEGIN
			INSERT INTO GIAOVIEN(MAGV, HOTEN, HOCVI, HOCHAM, GIOITINH, NGAYSINH, NGVAOLAM, HESO, MUCLUONG, MAKHOA)
			SELECT I.MAGV, I.HOTEN, I.HOCVI, I.HOCHAM, I.GIOITINH, I.NGAYSINH, I.NGVAOLAM, I.HESO, I.MUCLUONG, I.MAKHOA
			FROM inserted I
		END

END
GO

SELECT * 
FROM GIAOVIEN

INSERT INTO GIAOVIEN(MAGV, HOTEN, HOCVI, HOCHAM, GIOITINH, NGAYSINH, NGVAOLAM, HESO, MUCLUONG, MAKHOA) VALUES
('GV0145',	'Ho Thanh Son',	'PGS',	'GS',	0	,'1950-05-02',	'2004-01-11',	5,	2250000,	'KHMT')







--12. Học viên chỉ được thi lại (lần thi >1) khi điểm của lần thi trước đó dưới 5.
--13. Ngày thi của lần thi sau phải lớn hơn ngày thi của lần thi trước (cùng học viên,
--cùng môn học).



GO
CREATE OR ALTER TRIGGER T_LANTHI
ON KETQUATHI
INSTEAD OF INSERT
AS
BEGIN
	
	IF EXISTS (
		SELECT 1 
		FROM KETQUATHI INNER JOIN inserted I ON  KETQUATHI.MAHV = I.MAHV
											AND KETQUATHI.MAMH = I.MAMH
											
		GROUP BY I.MAHV, I.MAMH
		HAVING COUNT(*) >= 3)


		BEGIN
			RAISERROR ('THI QUA 3 LAN', 16,1)
			ROLLBACK TRANSACTION
		END




	IF EXISTS (
				SELECT 1
				FROM inserted I
				WHERE I.LANTHI <= 1)

		BEGIN
			INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, KQUA, DIEM)
			SELECT I.MAHV, I.MAMH, I.LANTHI, I.NGTHI, I.KQUA, I.DIEM
			FROM inserted I

		END

	ELSE 
		BEGIN 
			IF EXISTS (
						SELECT 1
						FROM inserted I JOIN KETQUATHI KQ ON KQ.MAMH = I.MAMH
														AND KQ.MAHV = I.MAHV
						WHERE 5< (
									SELECT  DIEM
									FROM KETQUATHI
									WHERE I.MAMH = KETQUATHI.MAMH
										AND I.MAHV = KETQUATHI.MAHV
										AND I.LANTHI -1 = KETQUATHI.LANTHI))

						BEGIN 
							RAISERROR('Học viên chỉ được thi lại (lần thi >1) khi điểm của lần thi trước đó dưới 5.',16,1)
							ROLLBACK TRANSACTION
						END




			IF EXISTS (
						SELECT 1
						FROM inserted I JOIN KETQUATHI KQ ON KQ.MAMH = I.MAMH
														AND KQ.MAHV = I.MAHV
						WHERE I.NGTHI< (
									SELECT  NGTHI
									FROM KETQUATHI
									WHERE I.MAMH = KETQUATHI.MAMH
										AND I.MAHV = KETQUATHI.MAHV
										AND I.LANTHI -1 = KETQUATHI.LANTHI))

						BEGIN 
							RAISERROR('Ngày thi của lần thi sau phải lớn hơn ngày thi của lần thi trước',16,1)
							ROLLBACK TRANSACTION
						END










				ELSE 
					BEGIN
						INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, KQUA, DIEM)
						SELECT I.MAHV, I.MAMH, I.LANTHI, I.NGTHI, I.KQUA, I.DIEM
						FROM inserted I
					END
			
		END 



END
GO


SELECT *
FROM KETQUATHI
WHERE MAHV ='K1102'

INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, KQUA, DIEM) VALUES 
	('K1102'	,'CSDL',	2	,'2001-12-28',	'Khong Dat'	,4.5)







--14. Giáo viên chỉ được phân công dạy những môn thuộc khoa giáo viên đó phụ trách

DROP TRIGGER T_GIANGDAY

GO
CREATE OR ALTER TRIGGER T_GIANGDAY
ON GIANGDAY
INSTEAD OF INSERT
AS
BEGIN
	IF EXISTS(	
				SELECT 1
				FROM inserted I 
					INNER JOIN GIAOVIEN GV ON GV.MAGV = I.MAGV
					INNER JOIN MONHOC MH ON MH.MAKHOA = I.MAMH
				WHERE GV.MAKHOA != MH.MAKHOA)


				
						BEGIN 
							RAISERROR('Giáo viên chỉ được phân công dạy những môn thuộc khoa giáo viên đó phụ trách',16,1)
							ROLLBACK TRANSACTION
						END
	
	ELSE
		BEGIN
			INSERT INTO GIANGDAY(MALOP, MAMH, MAGV, HOCKY, NAM, TUNGAY, DENNGAY)
			SELECT I.MALOP, I.MAMH, I.MAGV, I.HOCKY, I.NAM, I.TUNGAY, I.DENNGAY
			FROM inserted I
			PRINT 'THANH CONG'
		END

END
GO


INSERT INTO GIANGDAY(MALOP, MAMH, MAGV, HOCKY, NAM, TUNGAY, DENNGAY) VALUES
	('K11',	'CSDL',	'GV01',	1	,2006,	'2006-06-01',	'2006-07-15')



SELECT  * 
FROM GIANGDAY




--15. Mỗi học kỳ (của năm), một giáo viên được dạy tối đa 3 môn học
DROP TRIGGER IF EXISTS T_GIANGDAY

GO
CREATE OR ALTER TRIGGER T_GIANGDAY
ON GIANGDAY
INSTEAD OF INSERT 
AS
BEGIN
	IF EXISTS (
				SELECT 1
				FROM inserted I INNER JOIN GIANGDAY GD ON GD.MAGV = I.MAGV
				GROUP BY GD.MAGV, GD.HOCKY
				HAVING COUNT(*) >= 3)

			BEGIN 
				RAISERROR('Mỗi học kỳ (của năm), một giáo viên được dạy tối đa 3 môn học',16,1)
				ROLLBACK TRANSACTION
			END


		ELSE
			BEGIN
				INSERT INTO GIANGDAY(MALOP, MAMH,MAGV,HOCKY,NAM,TUNGAY,DENNGAY)
				SELECT I.MALOP, I.MAMH,I.MAGV,I.HOCKY,I.NAM,I.TUNGAY,I.DENNGAY
				FROM inserted I
			END
	
END
GO 

SELECT *
FROM GIANGDAY
WHERE MAGV = 'GV15' AND HOCKY =1

INSERT INTO GIANGDAY(MALOP, MAMH,MAGV,HOCKY,NAM,TUNGAY,DENNGAY) VALUES 
('K12',	'PTTKTT',	'GV15',	1	,2006,	'2006-01-02'	,'2006-05-12')




--16. Mức lương của giáo viên không được cao hơn mức lương của trưởng khoa

DROP TRIGGER IF EXISTS T_GIAOVIEN 


GO
CREATE OR ALTER TRIGGER T_GIAOVIEN
ON GIAOVIEN
INSTEAD OF INSERT
AS
BEGIN
	IF EXISTS (
				SELECT 1
				FROM inserted I
				WHERE I.MUCLUONG > (
									SELECT GIAOVIEN.MUCLUONG
									FROM GIAOVIEN INNER JOIN KHOA ON KHOA.MAKHOA = GIAOVIEN.MAKHOA
									WHERE GIAOVIEN.MAGV = KHOA.TRGKHOA 
										AND I.MAKHOA = GIAOVIEN.MAKHOA)
										)

			BEGIN 
				RAISERROR(' Mức lương của giáo viên không được cao hơn mức lương của trưởng khoa',16,1)
				ROLLBACK TRANSACTION
			END
				
	ELSE
		BEGIN
				INSERT INTO GIAOVIEN(MAGV, HOTEN, HOCVI, HOCHAM, GIOITINH,NGAYSINH,NGVAOLAM,HESO,MUCLUONG,MAKHOA)
				SELECT I.MAGV, I.HOTEN, I.HOCVI,I.HOCHAM, I.GIOITINH,I.NGAYSINH,I.NGVAOLAM,I.HESO,I.MUCLUONG,I.MAKHOA
				FROM inserted I
			END

END
GO


SELECT * FROM GIAOVIEN
WHERE MAGV='GV03'

INSERT INTO GIAOVIEN(MAGV, HOTEN, HOCVI, HOCHAM, GIOITINH,NGAYSINH,NGVAOLAM,HESO,MUCLUONG,MAKHOA) VALUES
('GV0100',	'QUOC HUNG'	,'PGS'	,'GS',	0	,'1950-05-02'	,'2004-01-11',	5	,9999999,'CNPM')

